import sendIcon from "../../public/assets/icons/send_icon.svg";
import nftIcon from "../../public/assets/icons/NFT.svg";
import piggyIcon from "../../public/assets/icons/piggy_icon.svg";
import whitelistIcon from "../../public/assets/icons/whitelist_icon.svg";
// import lensIcon from "../../public/assets/icons/Lens_icon.svg";
import rewardIcon from "../../public/assets/icons/reward_icon.svg";
import walletIcon from "../../public/assets/icons/Wallet_icon.svg";
import govIcon from "../../public/assets/icons/gov_icon.svg";
import adduserIcon from "../../public/assets/icons/adduser_icon.svg";
import removeUserIcon from "../../public/assets/icons/removeuser_icon.svg";
import moneyIcon from "../../public/assets/icons/money_icon.svg";
import { CHAIN_CONFIG } from "./constants";

export const proposalActionCommands = {
  0: "Distribute tokens to members",
  1: "Mint club token",
  2: "Modify governance",
  3: "Update total raise amount",
  4: "Send assets to an address",
  5: "Send nft to an address",
  6: "Add multisig signer",
  7: "Remove multisig signer",
  // 8: "Buy an NFT via Opensea",
  // 9: "Sell nft",
  10: "Whitelist addresses",
  // 11: "Whitelist Lens profile followers",
  // 12: "Whitelist addresses who commented on Lens post",
  13: "Update price per share",
  20: "Update total NFT supply",
  // 14: "Deposit tokens in AAVE pool",
  // 15: "Withdraw tokens from AAVE pool",
  // 16: "Whitelist addresses who mirrored Lens post",
  17: "Stake tokens through stargate",
  18: "Unstake tokens through stargate",
  // 19: "Swap tokens through uniswap",
  21: "Send tokens through csv",
  22: "Send tokens to all members",
  23: "Send tokens pro rata basis",
  24: "Deposit tokens with clip-finance",
  25: "Withdraw tokens with clip-finance",
  26: "Stake eth through eigen layer",
  27: "Remove stake from eigen layer",
};

export const PROPOSAL_MENU_ITEMS = (isGovernanceActive, tokenType) => {
  return [
    {
      key: 0,
      icon: rewardIcon,
      value: "Distribute tokens to members",
      text: "Distribute tokens to member(s)",
      section: "Administrative",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 1,
      icon: walletIcon,
      value: "Mint club token",
      text: "Mint station tokens",
      section: "Administrative",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 2,
      icon: govIcon,
      value: "Modify governance",
      text: "Modify governance",
      section: "Administrative",
      condition: () => isGovernanceActive,
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 3,
      icon: piggyIcon,
      value: "Update total raise amount",
      text: "Update total raise amount",
      section: "Deposits",
      condition: () => tokenType !== "erc721",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 13,
      icon: moneyIcon,
      value: "Update price per share",
      text: "Update price per share",
      section: "Deposits",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 20,
      icon: moneyIcon,
      value: "Update total NFT supply",
      text: "Update total NFT supply",
      section: "Deposits",
      condition: () => tokenType === "erc721",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 4,
      icon: sendIcon,
      value: "Send assets to an address",
      text: "Send assets to an address",
      section: "Manage Assets",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 5,
      value: "Send nft to an address",
      icon: nftIcon,
      text: "Send NFT",
      section: "Manage Assets",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    // {
    //   key: 8,
    //   value: "Buy an NFT via Opensea",
    //   text: "Buy an NFT via Opensea",
    //   section: "Manage Assets",
    // availableOnNetworkIds: [
    //   "0x89",
    //   "0x5",
    //   "0x1",
    //   "0x2105",
    //   "0xa4b1",
    //   "0xe708",
    //   "0x38",
    //   "0x1388",
    //   "0x64",
    //   "0x82750",
    //   "0xa9",
    //   "0x28c5f",
    // ],
    // },
    {
      key: 6,
      icon: adduserIcon,
      value: "Add multisig signer",
      text: "Add multisig signer",
      section: "Administrative",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 7,
      icon: removeUserIcon,
      value: "Remove multisig signer",
      text: "Remove multisig signer",
      section: "Administrative",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    {
      key: 10,
      icon: whitelistIcon,
      value: "Whitelist addresses",
      text: "Whitelist custom addresses",
      section: "Deposits",
      availableOnNetworkIds: [
        "0x89",
        "0x5",
        "0x1",
        "0x2105",
        "0xa4b1",
        "0xe708",
        "0x38",
        "0x1388",
        "0x64",
        "0x82750",
        "0xa9",
        "0x28c5f",
      ],
    },
    // {
    //   key: 11,
    //   icon: lensIcon,
    //   value: "Whitelist Lens profile followers",
    //   text: "Whitelist Lens profile followers",
    //   section: "Deposits",
    //   availableOnNetworkIds: [
    //     "0x89",
    //     "0x5",
    //     "0x1",
    //     "0x2105",
    //     "0xa4b1",
    //     "0xe708",
    //     "0x38",
    //     "0x1388",
    //     "0x64",
    //     "0x82750",
    //     "0xa9",
    //     "0x28c5f",
    //   ],
    // },
    // {
    //   key: 12,
    //   icon: lensIcon,
    //   value: "Whitelist addresses who commented on Lens post",
    //   text: "Whitelist comments on Lens post",
    //   section: "Deposits",
    //   availableOnNetworkIds: [
    //     "0x89",
    //     "0x5",
    //     "0x1",
    //     "0x2105",
    //     "0xa4b1",
    //     "0xe708",
    //     "0x38",
    //     "0x1388",
    //     "0x64",
    //     "0x82750",
    //     "0xa9",
    //     "0x28c5f",
    //   ],
    // },
    // {
    //   key: 16,
    //   icon: lensIcon,
    //   value: "Whitelist addresses who mirrored Lens post",
    //   text: "Whitelist Lens post mirrors",
    //   section: "Deposits",
    //   availableOnNetworkIds: [
    //     "0x89",
    //     "0x5",
    //     "0x1",
    //     "0x2105",
    //     "0xa4b1",
    //     "0xe708",
    //     "0x38",
    //     "0x1388",
    //     "0x64",
    //     "0x82750",
    //     "0xa9",
    //     "0x28c5f",
    //   ],
    // },
    // {
    //   key: 14,
    //   value: "Deposit tokens in AAVE pool",
    //   text: "AAVE Pool - Deposit",
    //   section: "DeFi Pools",
    //   availableOnNetworkIds: ["0x89"],
    // },
    // {
    //   key: 15,
    //   value: "Withdraw tokens from AAVE pool",
    //   text: "AAVE Pool - Withdraw",
    //   section: "DeFi Pools",
    //   availableOnNetworkIds: ["0x89"],
    // },
    {
      key: 17,
      value: "Stake tokens through stargate",
      text: "Stargate - Stake",
      section: "DeFi Pools",
      icon: sendIcon,
      availableOnNetworkIds: ["0x89", "0xe708"],
    },
    {
      key: 18,
      value: "Unstake tokens through stargate",
      text: "Stargate - Unstake",
      section: "DeFi Pools",
      icon: sendIcon,
      availableOnNetworkIds: ["0x89", "0xe708"],
    },
    // {
    //   key: 19,
    //   value: "Swap tokens through uniswap",
    //   text: "Uniswap - Swap",
    //   section: "Manage Assets",
    //   availableOnNetworkIds: ["0x89"],
    // },
    // {
    //   key: 21,
    //   value: "Send tokens through csv",
    //   text: "Send tokens through csv",
    //   section: "Manage Assets",
    //   icon: sendIcon,
    //   availableOnNetworkIds: ["0x89"],
    // },
    // {
    //   key: 22,
    //   value: "Send tokens to all members",
    //   text: "Send tokens to all members",
    //   section: "Manage Assets",
    //   icon: sendIcon,
    //   availableOnNetworkIds: ["0x89"],
    // },
    // {
    //   key: 23,
    //   value: "Send tokens pro rata basis",
    //   text: "Send tokens pro rata basis",
    //   section: "Manage Assets",
    //   icon: sendIcon,
    //   availableOnNetworkIds: ["0x89"],
    // },
  ];
};

export const DEFI_PROPOSALS = ({
  clipFinanceStaked = 0,
  staderETHStaked = 0,
  stargateStaked,
  kelpEthStaked,
  swellRswEthStaked,
  swellEigenEthStaked,
  networkId,
}) => {
  return [
    {
      name: "Clip Finance",
      logo: "/assets/images/clipFinanceLogo.png",
      APY: "17.36",
      staked: clipFinanceStaked,
      token: "USDC",
      executionIds: {
        Stake: 24,
        Unstake: 25,
      },
      availableOnNetworkIds: ["0xe708"],
      isUnstakeDisabled: true,
    },

    {
      name: "Stargate Finance",
      logo: "/assets/icons/stargate.png",
      APY: "11.34",
      staked: stargateStaked,
      token: "ETH",
      executionIds: {
        Stake: 17,
        Unstake: 18,
      },
      availableOnNetworkIds: ["0x89", "0xe708"],
      unstakeTokenAddress: CHAIN_CONFIG[networkId]?.stargateUnstakingAddresses
        ? CHAIN_CONFIG[networkId].stargateUnstakingAddresses[0]
        : "",
    },

    {
      name: "Stader x Eigen",
      logo: "/assets/icons/stader.png",
      APY: "17.36",
      staked: staderETHStaked,
      token: "ETH",
      executionIds: {
        Stake: 26,
        Unstake: 27,
      },
      availableOnNetworkIds: ["0x1"],
      unstakeTokenAddress: CHAIN_CONFIG[networkId]?.staderETHxAddress
        ? CHAIN_CONFIG[networkId].staderETHxAddress
        : "",
      isUnstakeDisabled: true,
    },

    {
      name: "Stader x Kelp",
      logo: "/assets/icons/kelp.png",
      APY: "8.2",
      staked: kelpEthStaked,
      token: "ETH",
      executionIds: {
        Stake: 31,
        Unstake: 32,
      },
      availableOnNetworkIds: ["0x1"],
      unstakeTokenAddress: CHAIN_CONFIG[networkId]?.kelpRsETHAddress
        ? CHAIN_CONFIG[networkId].kelpRsETHAddress
        : "",
      isUnstakeDisabled: true,
    },

    {
      name: "Swell - Restaking",
      logo: "/assets/icons/swell.png",
      APY: "7.9",
      staked: swellRswEthStaked,
      token: "ETH",
      executionIds: {
        Stake: 33,
        Unstake: 34,
      },
      availableOnNetworkIds: ["0x1"],
      unstakeTokenAddress: CHAIN_CONFIG[networkId]?.swellRswETHAddress
        ? CHAIN_CONFIG[networkId].swellRswETHAddress
        : "",
      isUnstakeDisabled: true,
    },

    {
      name: "Swell x Eigen",
      logo: "/assets/icons/swell_eigen.png",
      APY: "7.9",
      staked: swellEigenEthStaked,
      token: "ETH",
      executionIds: {
        Stake: 35,
        Unstake: 36,
      },
      availableOnNetworkIds: ["0x1"],
      isUnstakeDisabled: true,

      // unstakeTokenAddress: CHAIN_CONFIG[networkId]?.swellRswETHAddress
      //   ? CHAIN_CONFIG[networkId].swellRswETHAddress
      //   : "",
    },
  ];
};
